using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using ClosedXML.Excel;
using Microsoft.Win32;
using MoHinhTrongSo.ViewModel;


namespace MoHinhTrongSo
{
    /// <summary>
    /// Interaction logic for DuLieu.xaml
    /// </summary>
    public partial class DuLieu : Window
    {
        private DuLieuViewModel data;
        public DuLieu()
        {
            data = new DuLieuViewModel();
            InitializeComponent();
            this.DataContext = data;
            

        }

        public DuLieu(DuLieuViewModel dl)
        {
            data = dl;
            InitializeComponent();
            this.DataContext = data;
            
            Console.WriteLine("");
        }

        private void SetColumnSize()
        {
            foreach (var column in DataGrid.Columns)
            {
                column.MinWidth = column.ActualWidth;
                column.Width = 100;
                if (column.Header.ToString() == "")
                {
                    column.DisplayIndex = DataGrid.Columns.Count - 1;
                    
                }
            }

            var tsColumn = DataGrid.Columns[2] as DataGridTextColumn;
            
            tsColumn.Binding = new Binding(tsColumn.Header.ToString())
            {
                StringFormat = "{0:P0}"
            };
        }

        private void BtnXuat_Click(object sender, RoutedEventArgs e)
        {
            SaveFileDialog saveFileDialog = new SaveFileDialog
            {
                Filter = "Excel files (*.xlsx)|*.xlsx|All files (*.*)|*.*",
                Title = "Chọn file xuất ra",
            };
            

            if (saveFileDialog.ShowDialog() == true)
            {
                string fileName = saveFileDialog.FileName;
                

                try
                {
                    using (XLWorkbook workBook = new XLWorkbook())
                    {
                        var ws1 = workBook.Worksheets.Add("Dữ liệu");


                        var table = ws1.Cell(1, 1).InsertTable(data.ThongSoTable);

                        table.Column(2).Style.NumberFormat.NumberFormatId = 9;
                        ws1.Columns().AdjustToContents();

                        workBook.SaveAs(fileName);
                        ShowOk();
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.ToString());
                    ShowFail();
                }

            }
        }

        private void BtnTinh_Click(object sender, RoutedEventArgs e)
        {
            data.Tinh();
            
        }

        private void ShowOk()
        {
            string messageBoxText = "Thành công";
            string caption = "Thành công";
            MessageBoxButton button = MessageBoxButton.OK;
            MessageBoxImage icon = MessageBoxImage.Information;
            MessageBox.Show(messageBoxText, caption, button, icon);
        }

        private void ShowFail()
        {
            string messageBoxText = "Thất bại";
            string caption = "Thất bại";
            MessageBoxButton button = MessageBoxButton.OK;
            MessageBoxImage icon = MessageBoxImage.Error;
            MessageBox.Show(messageBoxText, caption, button, icon);
        }

        private void BtnThem_Click(object sender, RoutedEventArgs e)
        {

            if (!data.ThongSoTable.Columns.Contains(TxtCot.Text))
            {
                data.ThongSoTable.Columns.Add(TxtCot.Text, typeof(int));
                var column = new DataGridTextColumn
                {
                    Header = TxtCot.Text,
                    Binding = new Binding(TxtCot.Text)
                };

                DataGrid.Columns.Add(column);
                SetColumnSize();
            }
                
            
            
        }


        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            SetColumnSize();
        }
    }
}
